### ISSUE TITLE
24hr formatting

### ISSUE THREAD

**Issue by hunterwyork** [tsdataclinic/Vera#16]
Several cities have fully or partially unstandardized time formats in the output files (or at least in the links on the readme). I can't get your docker image up and running on my machine, so I can't replicate or fix the mistakes. Basically for all or a part of the data for each city, the PM indicators in the time/date data is dropped, causing many times to be in 12-hr format.

**Comment by jgrenadier** [comment]
I think I am hitting a similar issue with time formats.  I did get a docker image up and running but the generate_dataset.py generates exceptions:

loading data and assigning column types
loading file  /data/data/raw/NewOrleans/calls_2011.csv
HERE !!!!
Index(['NOPD_Item', 'Type_', 'TypeText', 'Priority', 'MapX', 'MapY',
       'TimeCreate', 'TimeDispatch', 'TimeArrive', 'TimeClosed', 'Disposition',
       'DispositionText', 'BLOCK_ADDRESS', 'Zip', 'PoliceDistrict',
       'Location'],
      dtype='object')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py",
 line 1856, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 200, in pandas._libs.tslibs.co
nversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_dataset.py", line 18, in <module>
    new_orleans.process_data()
  File "/data/src/cities/city.py", line 267, in process_data
    Geo.process(self)
  File "/data/src/features/geo.py", line 149, in process
    process_city(city)
  File "/data/src/features/geo.py", line 81, in process_city
    result = (city.pipe(rename_positional_columns, checkpoint='geo_positional')
  File "/data/src/cities/city.py", line 700, in pipe
    self.load_raw_data()
  File "/data/src/cities/city.py", line 121, in load_raw_data
    self.consolidate_all()
  File "/data/src/cities/city.py", line 219, in consolidate_all
    all_data.append( self.load_and_fix_types(str(file)))
  File "/data/src/cities/city.py", line 210, in load_and_fix_types
    data[column] = pd.to_datetime(data[column], format=column_date_format)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/tools/datetimes.py",
line 724, in to_datetime
    cache_array = _maybe_cache(arg, format, cache, convert_listlike)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/tools/datetimes.py",
line 152, in _maybe_cache
    cache_dates = convert_listlike(unique_dates, format)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/tools/datetimes.py",
line 447, in _convert_listlike_datetimes
    allow_object=True,
  File "/usr/local/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py",
 line 1861, in objects_to_datetime64ns
    raise e
  File "/usr/local/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py",
 line 1852, in objects_to_datetime64ns
    require_iso8601=require_iso8601,
  File "pandas/_libs/tslib.pyx", line 481, in pandas._libs.tslib.array_to_dateti
me
  File "pandas/_libs/tslib.pyx", line 620, in pandas._libs.tslib.array_to_dateti
me
ValueError: time data 01/01/2011 04:44:15 AM doesn't match format specified

**Comment by jgrenadier** [comment]
I have made some progress by editing NewOrleans.py:
was:
   DATE_FORMAT = '%Y-%m-%d %H:%M:%S.%f'
to:
    DATE_FORMAT = "%m/%d/%Y %I:%M:%S %p"  

It's taking along time to process so this may not be the only issue.
